### ISSUE TITLE
[Lecture Topic Task] - M2 Supple Design on Board for Domain Enhancement

### ISSUE THREAD

**Issue by frances-sepulveda** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#141]
Supple Design for the Board Component

Purpose: This Supple Design plan describes how to apply flexibility, usability, and extensibility to the Board component in the Multiplayer Dominoes project so that it's readily prepared for future updates and improvements. The design guarantees maintainability and modifiability of the Board component by establishing naming conventions that are understandable and intuitive functionality without having to delve into internal mechanisms, hence paving the way for seamless integration when newer milestones are desired.

Designing Conventions: Board constituent adheres to domain-driven design-class and function names come from the ubiquitous language of the project. Every method has been named in a readable fashion to be self-explainable for the developers, without actually having to open up the code behind it.

Scoring
Difficulty: 3
Urgency: 3

**Comment by rukitoyordan** [comment]
#### 1. Purpose of the Supple Design 
The objective is to adapt the design of the board and avatar customization in an intuitive manner, with adaptable elements that will manage new thematic elements. This design should satisfy the need for ease of understanding by users and the flexibility for modifications in the future.

#### 2. Naming and Domain-Driven Design
The class and function names come from Ubiquitous Language, a markup derived from the domain model. Name classes and functions in such a way that their responsibilities are implicitized and/or helps adhere to the project's domain-specific terminology in Multiplayer Dominoes.

#### Classes:
* `GameBoard`: Places, stores the state of, and lays out domino tiles on the board.
* `PlayerAvatar`: Controls the visual representation of the player, including customization.
* `TilePlacementValidator`: This checks if a tile placement action is an allowance according to the game rules.
* `ThemeManager`: Its role is to manage the board and avatar themes throughout a user selection.

##### Key Methods and Operations:
* `GameBoard.placeTile(tile, position)`: Possibly places the tile on the board at the position and informs about the state of the board.
* `PlayerAvatar.applyCustomization(options)`: Molds selected options onto avatar.
* `TilePlacementValidator IsValidPlacement(tile, boardState)`: Checks if a tile placement respects the rules of the game.
* `ThemeManager.applyTheme(theme)`: Applies a selected theme across both board and avatar components.

#### 3. Breakdown of Components and Supple Design Elements
a) Game Board Design
1. Central Structure and Flexibility
* `GameBoard`: Used for the main playing surface of the game as a space to render and control tiles.
Operation:
* `initializeBoard()`: Plants the board layout and initiates tile slots.
* `placeTile(tile, position)`: This would deal with placing any tile in a manner that it would look aligned considering the state of the board.
* `updateBoardState()`: Updates the board view among all players.

* Supple Design Features: The naming of each operation describes its purpose so that a developer can implement the operations without having to understand their implementation.

2. Interaction and Feedback End `TilePlacementValidator` - This one checks moves in real time.
Operations:
* `isValidPlacement(tile, boardState)`: Returns true if the placement of the tile is valid under the current game rules.
* `highlightValidMoves(playerTiles)`: Contains hints for the player regarding valid moves, improving user guidance.
* Agile Design Features: operations target validation and feedback as opposed to complex condition-checking logic, thus making the future rules easy to adjust to.
3. Thematic Flexibility
* `ThemeManager`: Provides management of the board's visual customisation to accommodate Puerto Rican and other cultural themes.
* Operations:
* `applyBoardTheme(theme)`: Applies a selected theme to the board's appearance.
* `toggleThemeEffect(effect)`: Adds/removes the effects, such as sound or animations bound to specific themes.
* Supple Design Features: Themes that can be easily changed without affecting the game's core logic.
b) Avatar Design 
1. Customization and Modularity
* `PlayerAvatar`: This would simply be the visual representation of a player in game.
* Operations:
* `applyCustomization(options)`: Applies selected user options to alters the avatar's rendering.
* `resetToDefault()`: Resets the avatar to its default state.
* **Flexible Design with Names: Such attractions are focused on specific actions related to customizing, allowing new developers to add or modify avatar features.
2. Thematic Synchronization
* `ThemeManager`: Ensures that board and avatar are of the same theme.
* Operations:
* `applyAvatarTheme(theme`): Applies selected theme elements on the avatar.
* `updateAvatarWithTheme(theme)`: Updates avatar parts based on current board theme.
* Supple Design Features: One manager to handle the various elements of the theme, so that it is easy to make changes throughout the game interface.

#### 4. Test Plan with Behavior-Driven Development
Write tests for each behavior before implementation to ensure a client-focused design and prevent internal dependency assumptions.
1. Board Testing
* Tile Placement Testing:
* Description: Validate that tiles are placed correctly based on game rules. Test Method: `test_validTilePlacement()`
* Expected Outcome: `isValidPlacement` should return true for valid moves and false otherwise.
2. Avatar Testing  - Application Test for Customization:
* Description: Verify that all available choices for the avatars' customization are applied and visible.
Test Method : `test_avatarCustomization()`
* Expected Tendency: `applyCustomization` shall update selected avatar's parts.
3. Theme Testing 
* Theme Application Across Components Test:
Description: Verify that the selected theme applies to both board and avatar elements (or like future powerups etc.).
* Testing Method: 
* `test_applyTheme()` - Expected Outcome: verify that `applyTheme` properly aligns board and avatar visuals. 
4. Extensibility Guidelines 
1. Add a new board or avatar themes - Add new themes to the `ThemeManager` without changing other components. - Extend the theme options using the `applyBoardTheme` and `applyAvatarTheme`. 
2. New Customization Options for Avatars - Extend the options parameter to add new features in `PlayerAvatar.applyCustomization:`.

**Comment by AngelCIICMorales** [comment]
The maximum score for a documentation task is 8. If you have any questions, please let me know.
