### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation - Narrative

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#194]
Please fix the section according to the following critique from the professor:

"The narrative should tell as a story, that which is important to understand how the domain works. For example, whether a player prefers a specific rule set is not really that interesting here (that would belong to some other section), but that there are different rule sets, that the rule set is decided before the game and not from round to round, etc. those things should be explained here."

Developer note:
Changed the narrative to shift its focus from individual players' preference for specific regional variations to setting out a broader explanation of how dominoes as a game work within a social and cultural context. The new version focuses on structural components of the game, such as the selection of rule sets before play and strategic depth of the game, rather than personal preference, which might be less relevant to the section.

**Comment by Gaby-Concepcion** [comment]
Changed the narrative to move the focus from individual players' preference for specific regional variations to setting out a broader explanation of how dominoes as a game work within a social and cultural context. The new version focuses on structural components of the game, such as the selection of rule sets before play and strategic depth of the game, rather than personal preference, which might be less relevant to the section.

**Comment by AngelCIICMorales** [comment]
Please add the changes in the description.
