### ISSUE TITLE
Create Video Presentation of the work done in Milestone 2

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#235]
The milestone ends in Oct 24th. After the milestone ends, speak with the managers @AngelCIICMorales and @Keiven-Soto to discuss what the team accomplished this milestone to show off in the video presentation that will be shown to the professor on Sept 23rd. You'll have till Oct 27th to submit the video but as the milestone will be over before then, the task score will be set for milestone 3

This presentation will need:

A powerpoint in which it shows what has been worked on this milestone (this will be another task) to work alongside with
A voiceover explaining the contents of the powerpoint
-* If possible a video demo of what we currently have for the web app

**Comment by Gaby-Concepcion** [comment]
Working on preparing a script and organizing slides for the video presentation, though I realized I do not have my laptop on which I run the project so in order to add a demo demonstration I would need someone to at the very least record a snippet to narrate over and slice into the video presentation.
