### ISSUE TITLE
[Lecture Topic Task] [Documentation Fix] Fix Milestone 2 Issues with Documentation - Implementation and Repository

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#372]
Please fix the section according to the following critique from the professor:

The business layer should be what we call the domain layer. Then the model would belong to the business layer, not to the persistence layer. But from the discussion in text, it seems that the model in this case is rather a data model and for that it's okay to count it to the persistence layer.

What is the function getAllUsers needed for from the perspective of the domain (or application)? If it's only to check whether a user already exists, then why not instead offer a function doesUserExist?

For the room repository you also provide a function getAll... what is it intended for? It's quite possible that you get all rooms just to then do something on them that should be a responsibility of the repository.

**Comment by JadiellMV** [comment]
@Keiven-Soto 
I modified the graph in the implementation section to match the new modifications, changed the Business layer to Domain layer as specified, added the model to the Domain Layer ("This layer will hold all the business logic that the system needs to meet the business rules. In most cases, it will contain the most logic. This layer defines Models that represent key domain concepts and serve as the foundation for the business logic. These models are decoupled from database schemas, ensuring they reflect business needs. The handler will interact with the Persistance layer by leveraging the appropriate repositories and any returning value will be passed back to the Presentation layer."), and deleted the model from the Persistance layer ("Note: the Models here are part of the Persistence layer since the Model is tightly coupled to the schema definition (we can say the Model represents more an ORM), but it can be part of both Business and Persistence layers. For the sake of simplicity, we decided to keep it like so. For next milestone, the Model will be decoupled to explicitly have an entity in the Business layer instead of the Persistence layer.").
![UpdatedImplementationDiagram](https://github.com/user-attachments/assets/22f0f6fe-9833-47d8-a639-e8b2883ec66e)
